# Generated by Django 5.0 on 2023-12-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0004_remove_task_completed_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('red', 'высокий'), ('yellow', 'средний'), ('green', 'низкий')], max_length=255),
        ),
    ]
