# Generated by Django 5.0 on 2023-12-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True),
        ),
    ]
