# Generated by Django 5.0 on 2023-12-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0006_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
