# Generated by Django 5.0 on 2023-12-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0007_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
